val lines = sc.textFile("twitter.edges") 
val words = lines.map(line => line.split(": "))
val wordList = words.flatMap(arr => {
	val followed = arr( 1 )
	val individ = followed.split(",")
	individ.map(indivi => (indivi, 1))
	})
val wordCounts = wordList.reduceByKey((a,b) => a+b)
wordCounts.saveAsTextFile("output1")
val wordsFinal = wordCounts.filter(a => a._2 > 1000)
wordsFinal.saveAsTextFile("output")
System.exit(0)