LOAD DATA LOCAL INFILE 'uniqueItems.dat' INTO TABLE Item FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueCategories.dat' INTO TABLE Category FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueSellers.dat' INTO TABLE Seller FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueBidders.dat' INTO TABLE Bidder FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'uniqueBids.dat' INTO TABLE Bid FIELDS TERMINATED BY '|*|';